#!/usr/bin/env bash

# bsp, stack or float
yabai -m config layout bsp
# yabai -m config --space 1 layout float
# BAR HEIGHT
BAR_HEIGHT=$(sketchybar -m --query bar | jq -r '.height')

GENERAL=(
	external_bar all:"${BAR_HEIGHT}":0
	split_type auto
	split_ratio 0.5
	auto_balance off
	insert_feedback_color 0xff7793d1
)

# padding
PADDING=(
    top_padding 20
    bottom_padding 12
    left_padding 12
    right_padding 12
    window_gap 12
)

# windows
WINDOWS=(
	window_placement second_child
	window_topmost on
	window_shadow float
	window_opacity on
	active_window_opacity 1.0
	normal_window_opacity 0.6
	#window_animation_duration 1.0
	window_origin_display focused
	window_opacity_duration 0.15
)

# borders
BORDERS=(
	window_border on
	window_border_blur off
	window_border_hidpi on
	window_border_width 2
	window_border_radius 12
	active_window_border_color 0xff7793d1
	normal_window_border_color 0xff5e6798
)

# mouse settings
MOUSE=(
	mouse_modifier alt
	mouse_action1 move
	mouse_action2 resize
	mouse_drop_action swap
    mouse_follows_focus off
)

# don't manage the following
UNMANAGED=(
    IINA
    1Password
    Activity Monitor
    App Store
    Calculator
    Finder
    System Information
    Software Update
    System Preferences
    System Settings
    zoom.us
    System Settings
    Firefox~Library
)
# Add settings
yabai -m config "${GENERAL[@]}"
yabai -m config "${PADDING[@]}"
yabai -m config "${WINDOWS[@]}"
yabai -m config "${BORDERS[@]}"
yabai -m config "${MOUSE[@]}"
# Add unmanaged apps
# for loop to add unmanaged apps
for app in "${UNMANAGED[@]}"; do
    # if the app name has ~ in it, use the second part as the title
    if [[ $app == *"~"* ]]; then
        app_name=$(echo "$app" | cut -d'~' -f1)
        app_title=$(echo "$app" | cut -d'~' -f2)
        yabai -m rule --add app="$app_name" title="$app_title" manage=off
    else
        yabai -m rule --add app="$app" manage=off
    fi
done

# Signal hooks
#yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
#yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
#yabai -m signal --add event=display_added action="sleep 1 && source $HOME/.local/bin/helper && create_spaces 7"
#yabai -m signal --add event=display_removed action="sleep 1 && source $HOME/.local/bin/helper && create_spaces 7"
#yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
#yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"
#:yabai -m signal --add event=window_created app="Code" action="source ${HOME}/.config/bin/helper && auto_stack Code"
